Jobs\ServiceBundle\Entity\JobsKeywords:
    type: entity
    table: jobs_keywords
    repositoryClass: Jobs\ServiceBundle\Entity\JobsKeywordsRepository
    fields:
        keywordId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: keyword_id
            generator:
                strategy: IDENTITY
        jobId:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: job_id
        keyword:
            type: string
            length: 40
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
