Jobs\ServiceBundle\Entity\JobsKeywords:
    type: entity
    table: jobs_keywords
    repositoryClass: Jobs\ServiceBundle\Entity\JobsKeywordsRepository
    fields:
        jobId:
            id: true
            type: string
            length: 100
            fixed: false
            nullable: false
            column: job_id
        keyword:
            id: true
            type: string
            length: 40
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
