Jobs\ServiceBundle\Entity\Jobs:
    type: entity
    repositoryClass: Jobs\ServiceBundle\Entity\JobsRepository
    table: jobs
    fields:
        jobId:
            id: true
            type: string
            length: 100
            fixed: false
            nullable: false
            column: job_id
        userId:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: user_id
        title:
            type: string
            length: 200
            fixed: false
            nullable: true
        number:
            type: string
            length: 255
            fixed: false
            nullable: true
        positionType:
            type: integer
            unsigned: false
            nullable: true
            column: position_type
        cityId:
            type: integer
            unsigned: false
            nullable: true
            column: city_id
        city:
            type: string
            length: 50
            fixed: false
            nullable: true
        state:
            type: string
            length: 50
            fixed: false
            nullable: true
        country:
            type: string
            length: 50
            fixed: false
            nullable: true
        areaCode:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: area_code
        zipcode:
            type: string
            length: 50
            fixed: false
            nullable: true
        skills:
            type: string
            length: 255
            fixed: false
            nullable: true
        description:
            type: text
            nullable: true
        applicationMethod:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: application_method
        applicationEmail:
            type: string
            length: 150
            fixed: false
            nullable: true
            column: application_email
        applicationEmailCc:
            type: string
            length: 150
            fixed: false
            nullable: true
            column: application_email_cc
        applicationUrl:
            type: string
            length: 500
            fixed: false
            nullable: true
            column: application_url
        showName:
            type: boolean
            nullable: true
            column: show_name
        showAddress1:
            type: boolean
            nullable: true
            column: show_address1
        showAddress2:
            type: boolean
            nullable: true
            column: show_address_2
        showCity:
            type: boolean
            nullable: true
            column: show_city
        showState:
            type: boolean
            nullable: true
            column: show_state
        showZipcode:
            type: boolean
            nullable: true
            column: show_zipcode
        showPhone:
            type: boolean
            nullable: true
            column: show_phone
        showEmail:
            type: boolean
            nullable: true
            column: show_email
        jobCreatedDt:
            type: bigint
            nullable: true
            column: job_created_dt
        jobModifiedDt:
            type: bigint
            nullable: true
            column: job_modified_dt
        jobDeletedDt:
            type: bigint
            nullable: true
            column: job_deleted_dt
        jobDeleted:
            type: integer
            unsigned: false
            nullable: false
            column: job_deleted
        jobStatus:
            type: integer
            unsigned: false
            nullable: false
            column: job_status
        latitude:
            type: float
            nullable: true
        longitude:
            type: float
            nullable: true
    lifecycleCallbacks: {  }
