Jobs\ServiceBundle\Entity\JobsPositionType:
    type: entity
    table: jobs_position_type
    repositoryClass: Jobs\ServiceBundle\Entity\JobsPositionTypeRepository
    fields:
        positionType:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: position_type
    oneToOne:
        job:
            targetEntity: Jobs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_id:
                    referencedColumnName: job_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
