Jobs\ServiceBundle\Entity\Users:
    type: entity
    repositoryClass: Jobs\ServiceBundle\Entity\UsersRepository
    table: users
    fields:
        userId:
            id: true
            type: string
            length: 100
            fixed: false
            nullable: false
            column: user_id
        email:
            type: string
            length: 150
            fixed: false
            nullable: true
        password:
            type: string
            length: 50
            fixed: false
            nullable: true
        accessLevel:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: access_level
        firstname:
            type: string
            length: 50
            fixed: false
            nullable: true
        lastname:
            type: string
            length: 50
            fixed: false
            nullable: true
        created:
            type: bigint
            nullable: true
        modified:
            type: bigint
            nullable: false
        deletedDt:
            type: bigint
            nullable: true
            column: deleted_dt
        deleted:
            type: integer
            unsigned: false
            nullable: false
        status:
            type: integer
            unsigned: false
            nullable: false
        userType:
            type: integer
            unsigned: false
            nullable: true
            column: user_type
        tempPassword:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: temp_password
    lifecycleCallbacks: {  }
