Jobs\ServiceBundle\Entity\JobsKeywords:
    type: entity
    table: jobs_keywords
    repositoryClass: Jobs\ServiceBundle\Entity\JobsKeywordsRepository
    fields:
        keyword:
            id: true
            type: string
            length: 40
            fixed: false
            nullable: false
    oneToOne:
        job:
            targetEntity: Jobs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_id:
                    referencedColumnName: job_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
