Jobs\ServiceBundle\Entity\Resumes:
    type: entity
    repositoryClass: Jobs\ServiceBundle\Entity\ResumesRepository
    table: resumes
    fields:
        resumeId:
            id: true
            type: string
            length: 100
            fixed: false
            nullable: false
            column: resume_id
            generator:
                strategy: IDENTITY
        userId:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: user_id
        resumeTitle:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: resume_title
        resumeShow:
            type: integer
            unsigned: false
            nullable: true
            column: resume_show
        resumeContent:
            type: text
            nullable: true
            column: resume_content
        resumeType:
            type: integer
            unsigned: false
            nullable: false
            column: resume_type
        resumeSkills:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: resume_skills
        resumeCreatedDt:
            type: bigint
            nullable: true
            column: resume_created_dt
        resumeModifiedDt:
            type: bigint
            nullable: true
            column: resume_modified_dt
        resumeDeletedTd:
            type: bigint
            nullable: true
            column: resume_deleted_td
        resumeStatus:
            type: integer
            unsigned: false
            nullable: false
            column: resume_status
        resumeDeleted:
            type: integer
            unsigned: false
            nullable: false
            column: resume_deleted
    lifecycleCallbacks: {  }
