<?php

namespace Jobs\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeoCountriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoCountriesRepository extends EntityRepository
{
}
