jobs_web_logout:
    pattern:  /auth/logout
    defaults: { _controller: JobsWebBundle:Auth:logout }

jobs_web_auth_register:
    pattern:  /auth/register
    defaults: { _controller: JobsWebBundle:Auth:register }

jobs_web_auth_login:
    pattern:  /auth/login
    defaults: { _controller: JobsWebBundle:Auth:login }

jobs_web_auth_forgot:
    pattern:  /auth/forgotPassword
    defaults: { _controller: JobsWebBundle:Auth:forgetPassword }

jobs_web_auth_reset:
    pattern:  /auth/resetPassword
    defaults: { _controller: JobsWebBundle:Auth:resetPassword }

jobs_web_employer_post:
    pattern:  /employer/post
    defaults: { _controller: JobsWebBundle:Employer:post }

jobs_web_employer_post_confirm:
    pattern:  /employer/post/confirm
    defaults: { _controller: FrameworkBundle:Template:template, template: 'JobsWebBundle:Employer:confirm.html.php' }

jobs_web_jobseeker_post:
    pattern:  /jobseeker/post
    defaults: { _controller: JobsWebBundle:Jobseeker:post }
jobs_web_jobseeker_preview:
    pattern:  /jobseeker/preview
    defaults: { _controller: JobsWebBundle:Jobseeker:preview }
jobs_web_home:
    pattern:  /
    defaults: { _controller: JobsWebBundle:Default:index }
