jobs_service_users_add:
    pattern:  /api/user/add
    defaults: { _controller: JobsServiceBundle:Users:add }
jobs_service_users_login:
    pattern:  /api/user/login
    defaults: { _controller: JobsServiceBundle:Users:login }
jobs_service_users_forgot:
    pattern:  /api/user/forgot
    defaults: { _controller: JobsServiceBundle:Users:forgot }
jobs_service_users_reset:
    pattern:  /api/user/reset
    defaults: { _controller: JobsServiceBundle:Users:reset }
examples:
    pattern:  /examples/index/{name}
    defaults: { _controller: JobsServiceBundle:Default:index }
examples_vars:
    pattern:  /examples/vars
    defaults: { _controller: JobsServiceBundle:Default:vars }
