<?php

namespace Jobs\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeoCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoCodesRepository extends EntityRepository
{
}
