jobs_service_users_add:
    pattern:  /api/user/add
    defaults: { _controller: JobsServiceBundle:Users:add }
jobs_service_users_login:
    pattern:  /api/user/login
    defaults: { _controller: JobsServiceBundle:Users:login }
jobs_service_users_forgot:
    pattern:  /api/user/forgot
    defaults: { _controller: JobsServiceBundle:Users:forgot }
jobs_service_users_reset:
    pattern:  /api/user/reset
    defaults: { _controller: JobsServiceBundle:Users:reset }
jobs_service_users_logout:
    pattern:  /api/user/logout
    defaults: { _controller: JobsServiceBundle:Users:logout }
jobs_service_users_details:
    pattern:  /api/user/details
    defaults: { _controller: JobsServiceBundle:Users:details }

examples:
    pattern:  /examples/index/{name}
    defaults: { _controller: JobsServiceBundle:Default:index }
examples_vars:
    pattern:  /examples/vars
    defaults: { _controller: JobsServiceBundle:Default:vars }
jobs_service_employer_post:
    pattern:  /api/employer/post
    defaults: { _controller: JobsServiceBundle:Employer:post }
jobs_service_resume_post:
    pattern:  /api/resume/post
    defaults: { _controller: JobsServiceBundle:Resume:post }
jobs_service_geo_countries:
    pattern:  /api/geo/countries
    defaults: { _controller: JobsServiceBundle:Geo:country }
jobs_service_geo_states:
    pattern:  /api/geo/states
    defaults: { _controller: JobsServiceBundle:Geo:state }
jobs_service_geo_cities:
    pattern:  /api/geo/cities
    defaults: { _controller: JobsServiceBundle:Geo:city }
