parameters:
#    jobs_service.example.class: Jobs\ServiceBundle\Example

services:
#    jobs_service.example:
#        class: %jobs_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
